# Generated by Django 4.2.28 on 2026-06-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testimonialsubmission',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
